# Generated by Django 5.0.4 on 2024-05-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status_count',
            field=models.IntegerField(default=0),
        ),
    ]
