# Generated by Django 5.0.6 on 2024-05-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_status_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='intra',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
