version: '3.8'

services:
  db:
    # build: /home/josephardev/Desktop/ft_transcendence/docker/postgres/
    image: postgres
    container_name: db_container
    restart: 'always'
    networks:
      - net
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=yoyahya
      - POSTGRES_PASSWORD=yoyahya
    volumes:
      - db:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  web:
    build: docker/django
    # command: daphne -e ssl:443:privateKey=private_daphne.pem:certKey=public_daphne.pem tests.asgi:application
    # command: daphne -e ssl:443:privateKey=private_daphne.pem:certKey=public_daphne.pem tests.asgi:application
    # command: daphne -b 0.0.0.0 -p 443 tests.asgi:application
    # restart: 'always'
    image: django_image
    container_name: djangocontainer
    volumes:
      - vol:/usr/src/
    networks:
      - net
    environment:
      - DJANGO_SETTINGS_MODULE=tests.settings
    depends_on:
      - db
    # ports:
    #   - 8001:8001
  server:
    build: docker/nginx/
    image: nginx_image
    container_name: nginx_container
    ports:
      - 443:443
    restart: 'always'
    volumes:
    - vol:/var/www/html/
    depends_on:
      - web
    networks:
      - net


networks:
    net:
      driver: bridge

volumes:
  vol:
    driver: local
    driver_opts:
      type: none
      device: .
      o: bind
  db:
    driver: local
    driver_opts:
      type: none
      device: ./database
      o: bind