services:
  - type: web
    name: db
    env: docker
    image: postgres
    containerName: db_container
    restartPolicy: always
    networks:
      - net
    envVarsFile: env.env
    volumes:
      - path: /var/lib/postgresql/data/
        name: db
    ports:
      - port: 5432
        targetPort: 5432
    healthCheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'"]
      intervalSeconds: 10
      timeoutSeconds: 3
      retries: 10

  - type: web
    name: backend
    env: docker
    dockerfilePath: ./Backend/Dockerfile
    image: backend_image
    containerName: djangocontainer
    restartPolicy: always
    networks:
      - net
    envVarsFile: env.env
    volumes:
      - path: /usr/src/media/
        name: media
    dependsOn:
      - serviceName: db
        condition: service_healthy

  - type: web
    name: server
    env: docker
    dockerfilePath: ./Frontend/Dockerfile
    image: frontend_image
    containerName: nginx_container
    restartPolicy: always
    ports:
      - port: 8000
        targetPort: 443
    volumes:
      - path: /var/www/html/media/
        name: media
    dependsOn:
      - serviceName: backend
    networks:
      - net

networks:
  - name: net
    driver: bridge

volumes:
  - name: media
  - name: db