services:
  - type: web
    name: db
    env: docker
    dockerfilePath: .
    buildCommand: ""
    envVars:
      - key: POSTGRES_USER
        value: $${POSTGRES_USER}
      - key: POSTGRES_DB
        value: $${POSTGRES_DB}
      - key: POSTGRES_PASSWORD
        value: $${POSTGRES_PASSWORD}
    disk:
      name: db
      mountPath: /var/lib/postgresql/data
      sizeGB: 10

  - type: web
    name: backend
    env: docker
    dockerfilePath: ./Backend/Dockerfile
    buildCommand: ""
    envVars:
      - key: ENV_FILE
        value: env.env
    disk:
      name: media
      mountPath: /usr/src/media
      sizeGB: 10
  - type: web
    name: server
    env: docker
    dockerfilePath: ./Frontend/Dockerfile
    buildCommand: ""
    disk:
      name: media
      mountPath: /var/www/html/media
      sizeGB: 10
