# Generated by Django 5.0.4 on 2024-05-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='re',
            field=models.IntegerField(default=0),
        ),
    ]
