# Generated by Django 5.0.6 on 2024-05-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_intra_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_2fa',
            field=models.BooleanField(default=True),
        ),
    ]
