# Generated by Django 5.0.7 on 2024-07-14 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoryMatch',
        ),
    ]
