# Generated by Django 5.0.4 on 2024-05-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='game_status',
            field=models.CharField(choices=[('in game', 'In Game'), ('waiting', 'Waiting')], default='waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=20),
        ),
    ]
