# Generated by Django 5.0.4 on 2024-05-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_game_status_alter_user_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='status',
            new_name='profile_status',
        ),
        migrations.AlterField(
            model_name='user',
            name='game_status',
            field=models.CharField(choices=[('in game', 'In Game'), ('waiting', 'Waiting'), ('no_game', 'No Game')], default='no_game', max_length=20),
        ),
    ]
