# Generated by Django 5.0.6 on 2024-05-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_is_2fa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_2fa',
            field=models.BooleanField(default=False),
        ),
    ]
