# Generated by Django 5.0.4 on 2024-06-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_status_user_profile_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='game_type',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
