# Generated by Django 5.0.4 on 2024-06-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_game_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_room',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
