# Generated by Django 5.0.4 on 2024-06-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_current_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tournament_wins',
            field=models.IntegerField(default=0),
        ),
    ]
