FROM debian:bullseye

RUN apt-get update && apt install -y nginx iputils-ping vim curl

# RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/nginx.conf

WORKDIR /var/www/html/templates/newSpa/

CMD ["nginx", "-g", "daemon off;"]