version: '3.8'

services:
  db:
    image: postgres
    container_name: db_container
    restart: 'always'
    networks:
      - net
    env_file: "env.env"
    volumes:
      - db:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 10
  backend:
    build: ./Backend/
    image: backend_image
    container_name: djangocontainer
    volumes:
      # - ./Backend:/usr/src/app
      - media:/usr/src/media/
    restart: 'always'
    networks:
      - net
    env_file: "env.env"
    depends_on:
      db:
        condition: service_healthy
  server:
    build: Frontend/
    image: frontend_image
    container_name: nginx_container
    ports:
      - 443:443
    restart: 'always'
    volumes:
    # - ./Frontend:/var/www/html/Frontend
    - media:/var/www/html/media/
    depends_on:
      - backend
    networks:
      - net


networks:
    net:
      driver: bridge
volumes:
  media: {}
  db: {}

# volumes:
#   vol:
#     driver: local
#     driver_opts:
#       type: none
#       device: .
#       o: bind
  # db:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     device: ./database
  #     o: bind