FROM python:3-slim

RUN apt-get update &&  pip install --upgrade pip  &&\
    apt-get install -y python3-psycopg2 openssl postgresql-client

COPY ./req.txt .
RUN pip install -r req.txt
COPY ./script.sh /
# COPY ./core /usr/src/app/
# COPY ./ft_transcendence /usr/src/app/
# COPY ./manage.py /usr/src/app/
COPY ./ /usr/src/

RUN chmod 777 /script.sh
WORKDIR /usr/src/
ENTRYPOINT ["/script.sh"]


# CMD []

# FROM debian:bullseye

# RUN apt-get update && \
#     apt-get install -y python3 pip iputils-ping vim curl python3-psycopg2 openssl
# COPY ./req.txt .
# RUN pip install -r req.txt
# RUN openssl req -x509 -nodes -days 365 -newkey rsa:4096 -keyout /usr/src/private_daphne.pem -out /usr/src/public_daphne.pem  -subj "/CN=pingpong"

# WORKDIR /usr/src/

# CMD ['python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py loaddata ss.json']