FROM python:3-slim

RUN apt-get update &&  pip install --upgrade pip  &&\
    apt-get install -y python3-psycopg2 openssl postgresql-client

COPY ./req.txt .
RUN pip install -r req.txt
COPY ./script.sh /
COPY ./ /usr/src/

RUN chmod 777 /script.sh
WORKDIR /usr/src/
ENTRYPOINT ["/script.sh"]