FROM debian:bullseye

RUN apt-get update && \
    apt-get install -y python3 pip iputils-ping vim curl python3-psycopg2 openssl
COPY ./req.txt .
RUN pip install -r req.txt

WORKDIR /usr/src/

CMD ['chmod +x /docker/django/script.sh && /docker/django/script.sh']
