FROM debian:bookworm-slim

RUN apt-get update && apt install -y nginx openssl
RUN openssl req -x509 -nodes -days 365 -newkey rsa:4096 -keyout /etc/ssl/private/nginx.pem -out /etc/ssl/certs/nginx.pem  -subj "/CN=pingpong"
COPY nginx.conf /etc/nginx/nginx.conf
COPY ./ /var/www/html
COPY ./default.jpg /var/www/html/media/
WORKDIR /var/www/html

CMD ["nginx", "-g", "daemon off;"]